####    NB    ####
#This is an example script on how to take the mean of all the sample dictionaries
#for each virus, generated by the sduc_CpGxxdicts.py scripts
##################


import pandas as pd

tab = pd.read_csv('CpGbridge_dict_samples.tsv', sep = '\t')

recl = list(tab['acc'])
recl = list(dict.fromkeys(recl))

thel = list(tab['dict'])

all_full = {}

i = 0

for rec in recl:

    all_full.update({rec:thel[i:(i+100)]})
    
    i = i + 100


all_mean = {}


for r in list(all_full):

    l = all_full[r]
    
    newd = {}

    for sd in l:

        d = eval(sd)
        
        for k in list(d):
        
                if k not in newd:
                        newd.update({k:[d[k]]})
                else:
                        newd[k].append(d[k])
                        
    fnd = {}
    
    for tk in list(newd):
    
        tl = newd[tk]
        
        av = sum(tl)/len(tl)
        
        fnd.update({tk:av})
        
    all_mean.update({r:fnd})
    
print(all_mean)